project_id = "ktvszjzryabjgxyobtyc"

[functions.extract-rib-data]
verify_jwt = false

[functions.generate-apporteur-invoice]
verify_jwt = false

[functions.delete-apporteur-invoice]
verify_jwt = false

[functions.recycle-stale-leads]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
