
CREATE TEMP TABLE IF NOT EXISTS import_clients (email text, full_name text);
TRUNCATE import_clients;
INSERT INTO import_clients (email, full_name) VALUES
('abdelaziz.bns@gmail.com', 'ABDELAZIZ AIT KHOUYA MOIH'),
('frid.abdelhadi@gmail.com', 'ABDELHADI FRID'),
('abdelkarimelmim@outlook.be', 'ABDELKARIM EL MIMOUNI'),
('abdellahbrdd@gmail.com', 'ABDELLAH BARRADA'),
('harat.abdelnacer@gmail.com', 'ABDELNACER HARAT'),
('dm-mamen071@hotmail.fr', 'ABDERRAHMANE RAMOUGA'),
('greenrachedi@gmail.com', 'ABDERRAOUF RACHEDI'),
('sissokoabdoulaziz@gmail.com', 'ABDOULAZIZ SISSOKO'),
('adibchowdhury2504@gmail.com', 'ADIB CHOWDHURY'),
('damdamadil84@gmail.com', 'ADIL DAMDAM'),
('aidabendadi@gmail.com', 'AIDA BENDADI'),
('akif.taser69@gmail.com', 'AKIF TASER'),
('alassana2001@gmail.com', 'ALASSANA JAWARA'),
('alimazouni42@gmail.com', 'ALI MAZOUNI'),
('amel.rai83@gmail.com', 'AMAL BOUKERCHA'),
('makked.amel@hotmail.com', 'AMEL MAKKED'),
('meila-mel@hotmail.fr', 'AMELLE ARRIOUI'),
('benouirane_amin@yahoo.fr', 'AMIN BEN OUIRANE'),
('saindouhalidiamina@gmail.com', 'AMINA SAINDOU HALIDI'),
('aminata.sangol@hotmail.com', 'AMINATA SANGOL'),
('soumareaminata2000@gmail.com', 'AMINATA SOUMARE'),
('amira.ghrandi@gmail.com', 'AMIRA SOUMEYA GHRANDI'),
('nonone.angelique78@outlook.com', 'ANGÉLIQUE NONONE'),
('anyaabbou@gmail.com', 'ANIA ABBOU'),
('anissa_2503@hotmail.com', 'ANISSA BAHAKA'),
('anissabelbey@gmail.com', 'ANISSA BELBEY'),
('salihasileman@gmail.com', 'ANSARA MOHAMED'),
('ant02ikari@hotmail.fr', 'ANTHONY SERRE'),
('asiaaitali@gmail.com', 'ASIA AIT ALI'),
('salam5944@gmail.com', 'ASLAM MOHAMED SHAFI'),
('asmaanajjar34@gmail.com', 'ASMA ANAJJAR'),
('chemamiasma4@gmail.com', 'ASMA CHEMAMI'),
('asma.elaissaoui47@gmail.com', 'ASMA EL AISSAOUI'),
('assia.bahida@hotmail.fr', 'ASSIA BAHIDA'),
('74.assia.maily@gmail.com', 'ASSIA EDDAOUDI'),
('atikaamahloude@hotmail.com', 'ATIKA AMAHLOUDE'),
('atika.arioua@yahoo.fr', 'ATIKA ARIOUA'),
('atika00@hotmail.fr', 'ATIKA SIDASSI'),
('aymerickudol@gmail.com', 'AYMERICK UDOL'),
('ayoub59210@gmail.com', 'AYOUB AMHIL'),
('azhar.missoma.pro@gmail.com', 'AZHAR MISSOMA'),
('azraa.jeetoo@hotmail.com', 'AZRAA JEETOO'),
('arecibopro@protonmail.com', 'AZZEDINE EL HADRI'),
('banayoumbouo@gmail.com', 'BANA KEYTA'),
('bobkar2a@gmail.com', 'BOBKAR EL AIDAOUI'),
('boubacar.sylla10@outlook.fr', 'BOUBACAR SYLLA'),
('bourwal10@gmail.com', 'BOUBACAR SIDDY DIALLO'),
('teamcd67@gmail.com', 'CÉLINE JANVIER'),
('ferrah.chaima@hotmail.fr', 'CHAIMA FERRAH'),
('miftah98chaimaa@gmail.com', 'CHAIMAA MIFTAH'),
('assiafeler@gmail.com', 'CHARLOTTE ROGNONI'),
('chemsedineba21@gmail.com', 'CHEMSEDINE BA'),
('bencherigui.cherine31@gmail.com', 'CHERINE BENCHERIGUI'),
('chimene.laiss@gmail.com', 'CHIMÈNE LAISSAOUI'),
('cindyzazanoas@gmail.com', 'CINDY KADI'),
('ribeiromonteiroc@gmail.com', 'CINTIA RIBEIRO MONTEIRO'),
('clarinobrasse18@gmail.com', 'CLARINO GIOVANNI BRASSE'),
('d.diallo1515@gmail.com', 'DICKO DIALLO'),
('tsoumou.dine@gmail.com', 'DINE TSOUMOU'),
('lekietsante@gmail.com', 'DJIBI BA'),
('djimdine.miscani976@gmail.com', 'DJIMDINE MISCANI'),
('donia.djedid@hotmail.fr', 'DONIA DJEDID'),
('drissouassi@gmail.com', 'DRISS OUASSI'),
('houdhayfa@hotmail.fr', 'EDDY (HOUDHAYFA) RATEL'),
('eliydad.grobri@gmail.com', 'ELIYDAD GROBRI'),
('elodievrard971@gmail.com', 'ELODIE EVRARD'),
('e.boukherrouba@gmail.com', 'EMELINE BOUKHERROUBA'),
('emma.merlin@hotmail.fr', 'EMMA MERLIN'),
('enis38boxing@gmail.com', 'ENIS KAIBA'),
('sergent.serviteur@gmail.com', 'FAÏZ ABDOULWAHAB'),
('far-1@hotmail.fr', 'FARIDA BOUDRIF'),
('yassouna7102011@gmail.com', 'FATIMA DHOUIB'),
('fbouchlaghem94@icloud.com', 'FATIMA BOUCHLAGHEM'),
('assminejolie@gmail.com', 'FATIMA MAHAMOUD'),
('zesauceso@gmail.com', 'FATIMA ZERIG'),
('bt.fatima@gmail.com', 'FATIMA DIARRA'),
('fatimalegoui95@gmail.com', 'FATIMA LEGOUI'),
('fatimadjamane15@gmail.com', 'FATIMA DJAMANE'),
('fatma.fikri@hotmail.com', 'FATMA SELIM'),
('fathiamtou14@gmail.com', 'FATOU THIAM'),
('fffd38000@gmail.com', 'FAYSA DEBZA'),
('fouad.benzerga@gmail.com', 'FOUAD BENZERGA'),
('fourahatimahamoud@gmail.com', 'FOURAHATI MAHAMOUD'),
('tmg.hadama@gmail.com', 'HADAMA TAMEGA'),
('hamida.sou32@sfr.fr', 'HAMIDA SULEIMAN'),
('hamzabouserhir@gmail.com', 'HAMZA BOUSERHIR'),
('hanae.manekoudi@gmail.com', 'HANAE MANEKOUDI'),
('hawa_sy@hotmail.com', 'HAWA GUISSE'),
('a.didi93@hotmail.fr', 'HEDI ABRIKH'),
('oumnaima2006@gmail.com', 'HÉLA BEN LAKHEL'),
('openbarbe@gmail.com', 'HOCINE MOUSSAOUI'),
('houdasml13@gmail.com', 'HODA SEMLALI'),
('houcine.sid@hotmail.com', 'HOUCINE SID ATMANE'),
('houda3005@yahoo.fr', 'HOUDA BEN HAMIDA'),
('ibrahimzagh84@gmail.com', 'IBRAHIM ZAGH'),
('ibsarr@outlook.fr', 'IBRAHIMA SARR'),
('idrissrelmy@gmail.com', 'IDRISS RELMY'),
('mezrouiihab2003@gmail.com', 'IHAB MEZROUI'),
('debboun90@gmail.com', 'IHSSANE DEBBOUN'),
('ilyass.rachdilaz@outlook.fr', 'ILYASS RACHDI'),
('ilkadi04@gmail.com', 'ILYES KADI'),
('ilyessou07@gmail.com', 'ILYES RADI'),
('elachi.imane123@gmail.com', 'IMANE EL ACHI'),
('imaneidmbark@gmail.com', 'IMANE ID M BARK'),
('ioana.insi@gmail.com', 'IOANA IONESI'),
('ismail.boukaiour510@gmail.com', 'ISMAIL BOUKAIOUR'),
('issaczerkoune123@gmail.com', 'ISSAC ZERKOUNE'),
('hachemijamel92@gmail.com', 'JAMEL HACHEMI'),
('juliengarcia89@proton.me', 'JULIEN GARCIA'),
('loubax75013@gmail.com', 'JULIEN HAUSTRAETE'),
('oummysawda@gmail.com', 'KADIDIATOU SEYDI'),
('kamarii.madi@gmail.com', 'KAMARIA MADI'),
('mekhloufkemil@gmail.com', 'KÉMIL MEKHLOUF'),
('khadija.settar@gmail.com', 'KHADIJA SETTAR'),
('aouinimadi@gmail.com', 'KHADRA AOUINI'),
('kyllianallal.pro@gmail.com', 'KYLIAN ALLAL'),
('aitlcen88@hotmail.fr', 'LAHCEN AIT HMID'),
('laila.bouteglifine@gmail.com', 'LAILA BOUTEGLIFINE'),
('laila.hrobalo@hotmail.fr', 'LAILA HASSOUNI'),
('ahamada-laza@hotmail.fr', 'LAZA AHAMADA'),
('lea.coraux@gmail.com', 'LÉA CORAUX'),
('lhammara@hotmail.com', 'LÉA HAMMARA'),
('hemissi.leilah@gmail.com', 'LEILA HEMISSI'),
('djendjelleila1@hotmail.com', 'LEILA DJENDJEL'),
('leila.gana@hotmail.fr', 'LEILA GANA'),
('bachouche.leila@orange.fr', 'LEILA (LILA) BACHOUCHE'),
('loukmane5@yahoo.fr', 'LOUKMANE KHALDI'),
('luqman.keyta@gmail.com', 'LUQMAN KEYTA'),
('maghniahammad@outlook.fr', 'MAGHNIA HAMMAD'),
('fof.mamadou023@gmail.com', 'MAHAMADOU FOFANA'),
('malaminedcr@gmail.com', 'MALAMINE JAFUNO'),
('meli.chougui@gmail.com', 'MALIKA CHOUGUI'),
('malikabelladjou@jotmail.fr', 'MALIKA BELLADJOU'),
('soltana.negafamb@gmail.com', 'MALIKA BOUYAHIAOUI'),
('b.manoubi@yahoo.fr', 'MANOUBI BOUSSANDEL'),
('mimiech25@gmail.com', 'MARIAM ECH CHETOUIA'),
('mariama3110@me.com', 'MARIAMA KANDE'),
('massireibnmoussa@gmail.com', 'MASSIRE MOUSSA DIAGOURAGA'),
('maylispradier6@gmail.com', 'MAŸLIS PRADIER'),
('melanie.aufildulien@gmail.com', 'MÉLANIE SMANIO'),
('mohamed.ankouri@gmail.com', 'MHAMED ANKOURI'),
('elmasmim@gmail.com', 'MIMOUNA AMMARI EL MASMOUDI'),
('mohamedouieb@hotmail.fr', 'MOHAMED DOUIEB'),
('mohamedjadi83@icloud.com', 'MOHAMED JADI'),
('m.fozir@yahoo.com', 'MOHAMED FOZIR'),
('m.amine.teraoui@gmail.com', 'MOHAMED AMINE TERAOUI'),
('mohamedaziz2405@gmail.com', 'MOHAMED AZIZ RAOUDI'),
('mohamednabil.seguer@gmail.com', 'MOHAMED NABIL SEGUER'),
('labsser.mla@gmail.com', 'MOHAMED-ILIYES LAHBOUB'),
('mohammedv493@gmail.com', 'MOHAMMED VINCENT'),
('malsaker@outlook.fr', 'MOHAMMED AL SAKERE'),
('mouhamedxiii@hotmail.com', 'MOUHAMED DIAWARA'),
('panpankomoukaramatou@gmail.com', 'MOUKARAMATOU PANPANKO'),
('s.hayet01@gmail.com', 'MOUNIR SAADI'),
('taieb.m@hotmail.com', 'MOURAD TAIEB'),
('moslide2@yahoo.fr', 'MOURAD FOUADLA'),
('moussataoucamara@gmail.com', 'MOUSSA CAMARA'),
('muhammedsalut5@gmail.com', 'MUHAMMED IBILI'),
('nabilmarz84@gmail.com', 'NABIL MARZOUK'),
('nabilkadid0@gmail.com', 'NABIL KADID'),
('philibertnabila2017@gmail.com', 'NABILA EL KHEMRI'),
('nadia38800@hotmail.fr', 'NADIA HOUMA'),
('nadiaouhh83@gmail.com', 'NADIA OUHA'),
('djerbi.nael@gmail.com', 'NAËL DJERBI'),
('sidaouinaima89@gmail.com', 'NAIMA SIDAOUI'),
('naima.boumaza@yahoo.fr', 'NAÏMA BOUMAZA'),
('moustic_najat@yahoo.fr', 'NAJAT MOUSTIC'),
('friend31@hotmail.fr', 'NAJAT EL KADI'),
('nargessebou@gmail.com', 'NARJESSE BOU'),
('nasriyanassur@gmail.com', 'NASRIYA NASSUR AHAMADI'),
('nassimachevallier@gmail.com', 'NASSIMA MENADI'),
('abdounatidja631@gmail.com', 'NATIDJA ABDOU'),
('nawel-barhdadi@live.fr', 'NAWEL BOUDGUIG'),
('ndeye53ndiaye@gmail.com', 'NDEYE NDIEME NDIAYE'),
('neyllamedini14@gmail.com', 'NEYLLA MEDINI'),
('sarikayanida6@gmail.com', 'NIDA SARIKAYA'),
('nesrine69100@hotmail.fr', 'NISRINE CHAROUITE'),
('nofohm@gmail.com', 'NOFOH MEITE'),
('nanou21301@hotmail.fr', 'NORA HEDJAM'),
('norhane940@gmail.com', 'NORHANE HADDACHI'),
('noureddine.eljabli@outlook.fr', 'NOUREDDINE EL JABLI'),
('obeidaaitmoha031@gmail.com', 'OBÉIDA AIT MOHA'),
('othmane.lakbiri@gmail.com', 'OTHMANE LAKBIRI'),
('oulaalhafian12@gmail.com', 'OULA RIZGALLA'),
('oumsadia.pro@gmail.com', 'OUMSADIA ASSANI'),
('mousmanemaiga@gmail.com', 'OUSMANE MAIGA'),
('bador3yn@gmail.com', 'RACHIDA BADOR'),
('rafikgoucem@gmail.com', 'RAFIK GOUCEM'),
('rafikelfatah0@gmail.com', 'RAFIK EL FATAH'),
('r-aihanhabsaoui@hotmail.com', 'RAIHAN HABSAOUI'),
('severrayan9@gmail.com', 'RAYAN SEVER'),
('rayhrami@gmail.com', 'RAYHANE RAMI'),
('lesoulie2017@gmail.com', 'RICHARD OULIÉ'),
('belaitiriyad@gmail.com', 'RIYAD BELAITI'),
('elbazkia@gmail.com', 'RKIA ELBAZ'),
('roihamatouabdallah763@gmail.com', 'ROIHAMATOU ABDALLAH COMBO'),
('rymelh15@gmail.com', 'RYM EL HAOUECH'),
('mastourryme@gmail.com', 'RYME MASTOUR'),
('aguourram.saadia@gmail.com', 'SAADIA AGUOURRAM'),
('sabrinadacunha03@gmail.com', 'SABRINA BOUNGAB'),
('sabrinagaidi86@gmail.com', 'SABRINA MECHRI'),
('sabrina.maziani75@gmail.com', 'SABRINA MAZIANI'),
('hennizourguis@gmail.com', 'SABRINE HENNI-ZOURGUI'),
('safwane69art@gmail.com', 'SAFWANE ARIOUAT'),
('djounaidsaid04@gmail.com', 'SAID DJOUNAID'),
('noorzen.massage@gmail.com', 'SAÏDA KHAIROUN'),
('salmablhn.pro@gmail.com', 'SALMA BOULEHIANE'),
('atiflpp@gmail.com', 'SALMA ATIF'),
('salma.elarabi16@gmail.com', 'SALMA EL ARABI'),
('samarresallem@gmail.com', 'SAMARRE SALLEM'),
('samiraakouh1@gmail.com', 'SAMIRA AKOUH'),
('vittasamra@gmail.com', 'SAMRA VITTA'),
('shirine21@hotmail.com', 'SANA NASSER'),
('sarah.elmoudni@hotmail.com', 'SARAH EL MOUNDI'),
('sarah_a@live.fr', 'SARAH ARBAOUI'),
('fretconnectlogistics@gmail.com', 'SIKINA SAID'),
('boukadidasirine.p@gmail.com', 'SIRINE BOUKADIDA'),
('belkacemsma@gmail.com', 'SMAIL BELKACEM'),
('samsoft10@hotmail.com', 'SOFIANE ALI MESSIAD'),
('sofya.benkaddour@gmail.com', 'SOFYA BENKADDOUR'),
('somya.boukhoubza.z@gmail.com', 'SOMYA BOUKHOUBZA'),
('soniah457@gmail.com', 'SONIA HAMIDA'),
('sonia.mohammad19@gmail.com', 'SONIA MOHAMMAD'),
('soraya.elb@gmail.com', 'SORAYA ELBIAD SEKKATE'),
('aitsouad31@gmail.com', 'SOUAD AIT ISAGUEN'),
('sofianebrouzi@hotmail.fr', 'SOUFIANE BROUZI'),
('oumydoug@gmail.com', 'SOUMIA DGHOUGHI'),
('soumibenabdallah@gmail.com', 'SOUMYA BENABDALLAH'),
('tjamal.r93@gmail.com', 'TARIQ ROUMANE'),
('vanessa.consultingpro@gmail.com', 'VANESSA CHERON'),
('dhib.vanessa@gmail.com', 'VANESSA DUBOIS'),
('joiwayra@gmail.com', 'VANESSA BADOL'),
('kossaiwael@gmail.com', 'WAËL KOSSAI'),
('gwassila@yahoo.fr', 'WASSILA KHALOUA'),
('yahqoub@hotmail.fr', 'YAKHOUBA TOURE'),
('sofimina12@outlook.fr', 'YAMINA ZNIDAH'),
('minaya.dahmich@gmail.com', 'YAMINA DAHMICH'),
('ursuletyann@gmail.com', 'YANN URSULET'),
('y.soyle@gmail.com', 'YASEMIN SOYLEMEZ'),
('yassar2005.ahamada@gmail.com', 'YASSAR AHAMADA'),
('yasserbys@gmail.com', 'YASSER BEN YOUNES'),
('yassine.elmorabit2007@gmail.com', 'YASSINE EL MORABIT'),
('ybenali9@gmail.com', 'YOUSRA BENALI'),
('elmansouriyoussef63@gmail.com', 'YOUSSEF EL MANSOURI'),
('super.nesquik10@gmail.com', 'YOUSSEF AASSILA'),
('youdjadou@gmail.com', 'YOUSSEF DJADOUDI'),
('zaheet040600@gmail.com', 'ZAHEER CHUKOORY'),
('zainabajustine@gmail.com', 'ZAINABA TOUMANI'),
('zakariawoni74@gmail.com', 'ZAKARIA WONI'),
('z.hebbar@outlook.fr', 'ZAKARIYA HEBBAR'),
('zeynepant@oulook.fr', 'ZEYNEP ATILGAN'),
('latrach.zied@hotmail.com', 'ZIED LATRACH'),
('lunazin@yahoo.fr', 'ZINA FRENDOU');
SELECT COUNT(*) AS n FROM import_clients;
