// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { isRunningInImpersonation } from '@/lib/impersonation';

export const SUPABASE_URL = "https://ktvszjzryabjgxyobtyc.supabase.co";
export const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0dnN6anpyeWFiamd4eW9idHljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIwMDQwODYsImV4cCI6MjA4NzU4MDA4Nn0.Hck5qF0GQ9-KEMvJiuu10-i-9562mEWBOBuHMTG33ZY";
const DEFAULT_STORAGE_KEY = "sb-ktvszjzryabjgxyobtyc-auth-token";
const IMPERSONATION_STORAGE_KEY = `${DEFAULT_STORAGE_KEY}-impersonation`;

// Impersonation is detected purely by host (view.albarakaecosysteme.com).
// This way the admin session on the main domain is never touched: different
// origins have separate localStorage buckets in the browser.
const isImpersonation = isRunningInImpersonation();

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    storageKey: isImpersonation ? IMPERSONATION_STORAGE_KEY : DEFAULT_STORAGE_KEY,
    persistSession: true,
    autoRefreshToken: true,
  }
});
